import schemdraw
import schemdraw.elements as elm
schemdraw.config(fontsize=11, lw=1.2)
B = lambda **k: elm.BjtNpn(circle=True, **k).theta(0)
with schemdraw.Drawing(file='lna_schematic.png', dpi=170, show=False) as d:
    # ---- Q1 input transistor + Le
    q1 = d.add(B().at((10, 0)).anchor('base').label('Q1  NX=8', loc='right', ofst=(0.25, 0)))
    d.add(elm.Inductor2(loops=3).down().at(q1.emitter).to((10.75, -2.2)).label('Le 32 pH', loc='bottom'))
    d.add(elm.Ground())
    # ---- Q2 cascode
    q2 = d.add(B().at((10, 2.4)).anchor('base').label('Q2  NX=8\n(cascode)', loc='right', ofst=(0.25, 0)))
    d.add(elm.Line().at(q1.collector).to(q2.emitter))
    d.add(elm.Line().at(q2.collector).to((10.75, 3.8)))
    d.add(elm.Dot().at((10.75, 3.8)))
    # ---- load: Lc || RP to VCC
    d.add(elm.Inductor2(loops=3).up().at((10.75, 3.8)).to((10.75, 5.8)).label('Lc 683 pH', loc='top'))
    d.add(elm.Line().at((10.75, 3.8)).to((12.2, 3.8)))
    d.add(elm.Resistor().up().at((12.2, 3.8)).to((12.2, 5.8)).label('RP 500 Ω', loc='bottom'))
    d.add(elm.Line().at((10.75, 5.8)).to((12.2, 5.8)))
    d.add(elm.Line().up().at((11.475, 5.8)).length(0.3))
    d.add(elm.Vdd().label('VCC 2.5 V'))
    # ---- output coupling
    d.add(elm.Dot().at((12.2, 3.8)))
    d.add(elm.Line().right().at((12.2, 3.8)).length(0.6))
    d.add(elm.Capacitor().right().label('Cout 51 fF'))
    d.add(elm.Dot(open=True).label('RF out → mixer', loc='right'))
    # ---- cascode base bias
    d.add(elm.Line().at(q2.base).to((8.8, 2.4)))
    d.add(elm.Dot().at((8.8, 2.4)))
    d.add(elm.Capacitor().down().at((8.8, 2.4)).to((8.8, 1.3)).label('Ccas\n5 pF', loc='bottom'))
    d.add(elm.Ground())
    d.add(elm.Line().at((8.8, 2.4)).to((7.3, 2.4)))
    d.add(elm.Dot().at((7.3, 2.4)).label('Vcas ≈ 1.86 V', loc='top', ofst=(0, 0.1)))
    d.add(elm.Resistor().up().at((7.3, 2.4)).to((7.3, 4.6)).label('R1 6 kΩ', loc='bottom'))
    d.add(elm.Vdd().label('VCC'))
    d.add(elm.Resistor().down().at((7.3, 2.4)).to((7.3, 1.2)).label('R2 19 kΩ', loc='top'))
    d.add(elm.Ground())
    # ---- RF input: Cin + Lb
    d.add(elm.Line().at(q1.base).to((9.4, 0)))
    d.add(elm.Dot().at((9.4, 0)))
    d.add(elm.Inductor2(loops=3).left().at((9.4, 0)).to((7.4, 0)).label('Lb 609 pH', loc='bottom'))
    d.add(elm.Capacitor().left().at((7.4, 0)).to((6.2, 0)).label('Cin 10 pF', loc='bottom'))
    d.add(elm.Dot(open=True).at((6.2, 0)).label('RF in\n(antenna, 50 Ω)', loc='top', ofst=(0, 0.15)))
    # ---- bias: Rb into base
    d.add(elm.Resistor().down().at((9.4, 0)).to((9.4, -3.8)).label('Rb 5 kΩ', loc='top'))
    d.add(elm.Dot().at((9.4, -3.8)))
    d.add(elm.Capacitor().down().at((9.4, -3.8)).to((9.4, -5.2)).label('Cbn 5 pF', loc='bottom'))
    d.add(elm.Ground())
    d.add(elm.Line().at((9.4, -3.8)).to((7.5, -3.8)))
    # Qf beta helper (emitter at bias node)
    qf = d.add(B().at((7.5, -3.8)).anchor('emitter').label('Qf β-helper', loc='right', ofst=(0.15, 0.55)))
    d.add(elm.Line().up().at(qf.collector).length(0.3))
    d.add(elm.Vdd().label('VCC'))
    d.add(elm.Line().at((7.5, -3.8)).to((7.5, -4.4)))
    d.add(elm.Dot().at((7.5, -4.4)))
    d.add(elm.SourceI().down().at((7.5, -4.4)).to((7.5, -6.0)).label('Ief 50 µA', loc='bottom'))
    d.add(elm.Ground())
    # Rref -> Qr (mirror reference)
    d.add(elm.Resistor().left().at((7.5, -4.4)).to((5.5, -4.4)).label('Rref 40 kΩ', loc='bottom'))
    qr = d.add(B().reverse().at((5.5, -4.4)).anchor('base').label('Qr NX=1\n(mirror ref)', loc='left', ofst=(-0.45, 0)))
    d.add(elm.Ground().at(qr.emitter))
    d.add(elm.Line().at(qr.collector).to((4.75, -3.1)))
    d.add(elm.Dot().at((4.75, -3.1)))
    d.add(elm.Line().at((4.75, -3.1)).to(qf.base))
    d.add(elm.SourceI().up().at((4.75, -3.1)).to((4.75, -1.7)).label('Iref\n0.92 mA', loc='bottom'))
    d.add(elm.Vdd().label('VCC'))
    # title
    d.add(elm.Label().at((8.5, 7.0)).label('24 GHz LNA — cascode HBT, inductive degeneration, current-mirror bias', fontsize=13))
