import schemdraw
import schemdraw.elements as elm
schemdraw.config(fontsize=11, lw=1.2)
B = lambda **k: elm.BjtNpn(circle=True, **k).theta(0)
with schemdraw.Drawing(file='pa_schematic.png', dpi=170, show=False) as d:
    # ---- Q1 with emitter degeneration
    q1 = d.add(B().at((10, 0)).anchor('base').label('Q1  npn13G2\nNX=8', loc='right', ofst=(0.25, 0)))
    d.add(elm.Resistor().down().at(q1.emitter).to((10.75, -2.0)).label('Re1 5 Ω', loc='bottom'))
    d.add(elm.Ground())
    # ---- Q2 cascode (high-voltage HBT)
    q2 = d.add(B().at((10, 2.4)).anchor('base').label('Q2  npn13G2v\nNX=8 (high-voltage)', loc='right', ofst=(0.25, 0)))
    d.add(elm.Line().at(q1.collector).to(q2.emitter))
    d.add(elm.Line().at(q2.collector).to((10.75, 3.8)))
    d.add(elm.Dot().at((10.75, 3.8)))
    # ---- output match: shunt Lc to VCC + series Cout
    d.add(elm.Inductor2(loops=3).up().at((10.75, 3.8)).to((10.75, 5.8)).label('Lc 543 pH', loc='top'))
    d.add(elm.Vdd().label('VCC 2.5 V'))
    d.add(elm.Line().right().at((10.75, 3.8)).length(1.2))
    d.add(elm.Capacitor().right().label('Cout 71 fF'))
    d.add(elm.Dot(open=True).label('to TX antenna\n(50 Ω)', loc='right'))
    # ---- cascode base bias
    d.add(elm.Line().at(q2.base).to((8.8, 2.4)))
    d.add(elm.Dot().at((8.8, 2.4)))
    d.add(elm.Capacitor().down().at((8.8, 2.4)).to((8.8, 1.3)).label('Ccas\n5 pF', loc='bottom'))
    d.add(elm.Ground())
    d.add(elm.Line().at((8.8, 2.4)).to((7.6, 2.4)))
    d.add(elm.Dot(open=True).at((7.6, 2.4)).label('Vcas 1.6 V', loc='left'))
    # ---- RF input from LO buffer driver 2
    d.add(elm.Line().at(q1.base).to((9.2, 0)))
    d.add(elm.Dot().at((9.2, 0)))
    d.add(elm.Capacitor().left().at((9.2, 0)).to((7.6, 0)).label('Cin 1 pF', loc='bottom'))
    d.add(elm.Dot(open=True).at((7.6, 0)).label('LO from buffer driver 2 (~0.35 V)', loc='top', ofst=(-0.6, 0.15)))
    # ---- bias feed
    d.add(elm.Resistor().down().at((9.2, 0)).to((9.2, -3.0)).label('Rb 1 kΩ', loc='bottom'))
    d.add(elm.Dot().at((9.2, -3.0)))
    d.add(elm.Capacitor().down().at((9.2, -3.0)).to((9.2, -4.4)).label('Cbn 5 pF', loc='bottom'))
    d.add(elm.Ground())
    d.add(elm.Line().at((9.2, -3.0)).to((7.5, -3.0)))
    qf = d.add(B().at((7.5, -3.0)).anchor('emitter'))
    d.add(elm.Label().at((8.05, -2.55)).label('Qf'))
    d.add(elm.Line().up().at(qf.collector).length(0.3)); d.add(elm.Vdd().label('VCC'))
    d.add(elm.Line().at((7.5, -3.0)).to((7.5, -3.6))); d.add(elm.Dot().at((7.5, -3.6)))
    d.add(elm.SourceI().down().at((7.5, -3.6)).to((7.5, -5.2)).label('Ief 50 µA', loc='bottom'))
    d.add(elm.Ground())
    d.add(elm.Resistor().left().at((7.5, -3.6)).to((5.5, -3.6)).label('Rref 8 kΩ', loc='bottom'))
    qr = d.add(B().reverse().at((5.5, -3.6)).anchor('base'))
    d.add(elm.Label().at((3.85, -3.6)).label('Qr NX=1\n(mirror ref)'))
    d.add(elm.Resistor().down().at(qr.emitter).to((4.75, -5.4)).label('40 Ω', loc='top'))
    d.add(elm.Ground())
    d.add(elm.Line().at(qr.collector).to((4.75, -2.3))); d.add(elm.Dot().at((4.75, -2.3)))
    d.add(elm.Line().at((4.75, -2.3)).to(qf.base))
    d.add(elm.SourceI().up().at((4.75, -2.3)).to((4.75, -0.9)).label('Iref\n0.78 mA', loc='bottom'))
    d.add(elm.Vdd().label('VCC'))
    d.add(elm.Label().at((9.0, 7.1)).label('24 GHz PA — single-ended cascode, degenerated input, high-voltage cascode device', fontsize=13))
